kind: pipeline
name: default

steps:
  - name: Test with perl 5.28
    image: gugod/perl-testbox:5.28
    commands:
      - cpanm --installdeps .
      - cpanm -n Test2::Harness
      - yath --qvf

  - name: Build the distribution
    image: gugod/perl-testbox:5.28
      - cpanm -n App::ModuleBuildTiny
      - mbtiny dist

  - name: Install Distribution
    image: perl:5.28.0
    commands:
      - ls -l
      - cpanm -q *.tar.gz
